INSERT INTO GAME (ID, CURRENT_QUESTION_IDX, NUM_SECONDS_BETWEEN_QUESTIONS, NUM_SECONDS_PER_QUESTION, STATE) VALUES
(1, 0, 10, 10, 'NOT_STARTED');

INSERT INTO QUESTION (ID, TEXT, OPTIONA, OPTIONB, OPTIONC, OPTIOND, CORRECT_ANSWER) VALUES
(1, 'What percentage of babies actually arrive on their due date?',
'Less than 2%',
'3-4%',
'10%',
'25%',
'B');

INSERT INTO QUESTION (ID, TEXT, OPTIONA, OPTIONB, OPTIONC, OPTIOND, CORRECT_ANSWER) VALUES
(2, 'Babies are born without which body part?',
'Kneecaps',
'Elbows',
'Tailbone',
'Shoulder Blades',
'B');

INSERT INTO GAME_QUESTIONS (GAME_ID, QUESTIONS_ID) VALUES (1, 1);
INSERT INTO GAME_QUESTIONS (GAME_ID, QUESTIONS_ID) VALUES (1, 2);

INSERT INTO USER (name, token, admin, score) VALUES ('admin', 'batman', true, 0);